using NUnit.Framework;
using TestGenerator.Core.Generation;
using TestGenerator.Core.Models;

namespace TestGenerator.Tests.Generation;

[TestFixture]
public class NUnitTestGeneratorTests
{
    private NUnitTestGenerator _generator;
    
    [SetUp]
    public void SetUp()
    {
        _generator = new NUnitTestGenerator();
    }
    
    [Test]
    public void GenerateTestClass_ForSimpleClass_ShouldGenerateValidTestClass()
    {
        var classInfo = new ClassInfo
        {
            Name = "Calculator",
            Namespace = "MyApp",
            PublicMethods = new List<MethodInfo>
            {
                new MethodInfo { Name = "Add", ReturnType = "int" }
            }
        };
        
        var result = _generator.GenerateTestClass(classInfo);
        
        Assert.That(result, Does.Contain("[TestFixture]"));
        Assert.That(result, Does.Contain("public class CalculatorTests"));
        Assert.That(result, Does.Contain("namespace MyApp.Tests"));
        Assert.That(result, Does.Contain("private Calculator _calculatorUnderTest"));
        Assert.That(result, Does.Contain("[SetUp]"));
        Assert.That(result, Does.Contain("[Test]"));
        Assert.That(result, Does.Contain("public void Add_Test()"));
        Assert.That(result, Does.Contain("Assert.Fail(\"autogenerated\")"));
    }
    
    [Test]
    public void GenerateTestClass_ForClassWithMultipleMethods_ShouldGenerateMultipleTests()
    {
        var classInfo = new ClassInfo
        {
            Name = "Processor",
            Namespace = "MyApp",
            PublicMethods = new List<MethodInfo>
            {
                new MethodInfo { Name = "Start", ReturnType = "void" },
                new MethodInfo { Name = "Stop", ReturnType = "void" },
                new MethodInfo { Name = "GetStatus", ReturnType = "string" }
            }
        };
        
        var result = _generator.GenerateTestClass(classInfo);
        
        Assert.That(result, Does.Contain("public void Start_Test()"));
        Assert.That(result, Does.Contain("public void Stop_Test()"));
        Assert.That(result, Does.Contain("public void GetStatus_Test()"));
    }
    
    [Test]
    public void GenerateTestClass_ForMethodWithParameters_ShouldGenerateArrangeSection()
    {
        var classInfo = new ClassInfo
        {
            Name = "Calculator",
            Namespace = "MyApp",
            PublicMethods = new List<MethodInfo>
            {
                new MethodInfo 
                { 
                    Name = "Add", 
                    ReturnType = "int",
                    Parameters = new List<ParameterInfo>
                    {
                        new ParameterInfo { Name = "a", Type = "int" },
                        new ParameterInfo { Name = "b", Type = "int" }
                    }
                }
            }
        };
        
        var result = _generator.GenerateTestClass(classInfo);
        
        Assert.That(result, Does.Contain("int a = default!;"));
        Assert.That(result, Does.Contain("int b = default!;"));
        Assert.That(result, Does.Contain("var actual = _calculatorUnderTest.Add(a, b);"));
        Assert.That(result, Does.Contain("int expected = default!;"));
    }
    
    [Test]
    public void GenerateTestClass_ForVoidMethod_ShouldNotHaveReturnAssert()
    {
        var classInfo = new ClassInfo
        {
            Name = "Logger",
            Namespace = "MyApp",
            PublicMethods = new List<MethodInfo>
            {
                new MethodInfo { Name = "Log", ReturnType = "void" }
            }
        };
        
        var result = _generator.GenerateTestClass(classInfo);
        
        Assert.That(result, Does.Contain("_loggerUnderTest.Log();"));
        Assert.That(result, Does.Not.Contain("var actual ="));
        Assert.That(result, Does.Not.Contain("expected = default!;"));
        Assert.That(result, Does.Contain("Assert.Fail(\"autogenerated\")"));
    }
    
    [Test]
    public void GenerateTestClass_ForOverloadedMethods_ShouldGenerateUniqueTestNames()
    {
        var classInfo = new ClassInfo
        {
            Name = "Converter",
            Namespace = "MyApp",
            PublicMethods = new List<MethodInfo>
            {
                new MethodInfo 
                { 
                    Name = "Convert", 
                    ReturnType = "int",
                    Parameters = new List<ParameterInfo>
                    {
                        new ParameterInfo { Name = "value", Type = "int" }
                    }
                },
                new MethodInfo 
                { 
                    Name = "Convert", 
                    ReturnType = "double",
                    Parameters = new List<ParameterInfo>
                    {
                        new ParameterInfo { Name = "value", Type = "double" }
                    }
                }
            }
        };
        
        var result = _generator.GenerateTestClass(classInfo);
        
        Assert.That(result, Does.Contain("public void Convert_int_Test()"));
        Assert.That(result, Does.Contain("public void Convert_double_Test()"));
    }
    
    [Test]
    public void GenerateTestClass_WhenNoNamespace_ShouldNotAddNamespaceBlock()
    {
        var classInfo = new ClassInfo
        {
            Name = "GlobalClass",
            Namespace = string.Empty,
            PublicMethods = new List<MethodInfo>
            {
                new MethodInfo { Name = "Method", ReturnType = "void" }
            }
        };
        
        var result = _generator.GenerateTestClass(classInfo);
        
        Assert.That(result, Does.Not.Contain("namespace"));
        Assert.That(result, Does.Contain("[TestFixture]"));
        Assert.That(result, Does.Contain("public class GlobalClassTests"));
    }
}