using System.Text;
using TestGenerator.Core.Models;

namespace TestGenerator.Core.Generation;

public class NUnitTestGenerator : ITestGenerator
{
    public string GenerateTestClass(ClassInfo classInfo)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("using NUnit.Framework;");
        sb.AppendLine();
        
        if (!string.IsNullOrEmpty(classInfo.Namespace))
        {
            sb.AppendLine($"namespace {classInfo.Namespace}.Tests");
            sb.AppendLine("{");
        }
        
        sb.AppendLine($"    [TestFixture]");
        sb.AppendLine($"    public class {classInfo.Name}Tests");
        sb.AppendLine($"    {{");
        
        var fieldName = $"_{char.ToLower(classInfo.Name[0])}{classInfo.Name.Substring(1)}UnderTest";
        sb.AppendLine($"        private {classInfo.Name} {fieldName};");
        sb.AppendLine();
        
        sb.AppendLine($"        [SetUp]");
        sb.AppendLine($"        public void SetUp()");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            {fieldName} = new {classInfo.Name}();");
        sb.AppendLine($"        }}");
        sb.AppendLine();
        
        foreach (var method in classInfo.PublicMethods)
        {
            GenerateTestMethod(sb, method, classInfo, fieldName);
        }
        
        sb.AppendLine($"    }}");
        
        if (!string.IsNullOrEmpty(classInfo.Namespace))
        {
            sb.AppendLine($"}}");
        }
        
        return sb.ToString();
    }
    
    private void GenerateTestMethod(StringBuilder sb, MethodInfo method, ClassInfo classInfo, string fieldName)
    {
        var testName = method.Name;
        if (method.Parameters.Any())
        {
            var paramSuffix = string.Join("_", method.Parameters.Select(p => 
                p.Type.Replace("?", "").Replace("<", "_").Replace(">", "_").Replace("[]", "Array")));
            testName = $"{method.Name}_{paramSuffix}";
        }
        
        sb.AppendLine($"        [Test]");
        sb.AppendLine($"        public void {testName}_Test()");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            // Arrange");
        
        foreach (var param in method.Parameters)
        {
            sb.AppendLine($"            {param.Type} {param.Name} = default!;");
        }
        
        sb.AppendLine();
        sb.AppendLine($"            // Act");
        
        var callParams = string.Join(", ", method.Parameters.Select(p => p.Name));
        if (method.IsVoid)
        {
            sb.AppendLine($"            {fieldName}.{method.Name}({callParams});");
        }
        else
        {
            sb.AppendLine($"            var actual = {fieldName}.{method.Name}({callParams});");
        }
        
        sb.AppendLine();
        sb.AppendLine($"            // Assert");
        
        if (!method.IsVoid)
        {
            sb.AppendLine($"            {method.ReturnType} expected = default!;");
            sb.AppendLine($"            Assert.That(actual, Is.EqualTo(expected));");
        }
        
        sb.AppendLine($"            Assert.Fail(\"autogenerated\");");
        sb.AppendLine($"        }}");
        sb.AppendLine();
    }
}