using NUnit.Framework;
using TestGenerator.Core.Generation;
using TestGenerator.Core.Pipeline;

namespace TestGenerator.Tests.Integration;

[TestFixture]
public class PipelineIntegrationTests
{
    private string _tempDir;
    
    [SetUp]
    public void SetUp()
    {
        _tempDir = Path.Combine(Path.GetTempPath(), $"IntegrationTest_{Guid.NewGuid()}");
        Directory.CreateDirectory(_tempDir);
    }
    
    [TearDown]
    public void TearDown()
    {
        if (Directory.Exists(_tempDir))
        {
            try
            {
                Directory.Delete(_tempDir, true);
            }
            catch
            {
            }
        }
    }
    
    [Test]
    public async Task EndToEnd_WithRealClass_ShouldGenerateCompilableTests()
    {
        var inputDir = Path.Combine(_tempDir, "Input");
        var outputDir = Path.Combine(_tempDir, "Output");
        Directory.CreateDirectory(inputDir);
        Directory.CreateDirectory(outputDir);
        
        var testClassCode = @"
using System;

public class Calculator
{
    public int Add(int a, int b) => a + b;
    
    public void Clear() { }
    
    public string Format(string input) => input?.ToUpper() ?? string.Empty;
}";
        
        var inputFile = Path.Combine(inputDir, "Calculator.cs");
        await File.WriteAllTextAsync(inputFile, testClassCode);
        
        var pipeline = new TestGenerationPipeline(new NUnitTestGenerator());
        
        await pipeline.ProcessAsync(new[] { inputFile }, outputDir);
        
        var generatedFile = Path.Combine(outputDir, "CalculatorTests.cs");
        Assert.That(File.Exists(generatedFile), Is.True);
        
        var generatedCode = await File.ReadAllTextAsync(generatedFile);
        
        Assert.That(generatedCode, Does.Contain("using NUnit.Framework;"));
        Assert.That(generatedCode, Does.Contain("[TestFixture]"));
        Assert.That(generatedCode, Does.Contain("public class CalculatorTests"));
        
        Assert.That(generatedCode, Does.Contain("public void Add_Test()"));
        Assert.That(generatedCode, Does.Contain("public void Clear_Test()"));
        Assert.That(generatedCode, Does.Contain("public void Format_Test()"));
        
        Assert.That(generatedCode, Does.Contain("// Arrange"));
        Assert.That(generatedCode, Does.Contain("// Act"));
        Assert.That(generatedCode, Does.Contain("// Assert"));
        
        Assert.That(generatedCode, Does.Contain("int a = default!;"));
        Assert.That(generatedCode, Does.Contain("int b = default!;"));
        Assert.That(generatedCode, Does.Contain("string input = default!;"));
        
        Assert.That(generatedCode, Does.Contain("Assert.Fail(\"autogenerated\")"));
    }
    
    [Test]
    public async Task EndToEnd_WithMultipleFiles_ShouldGenerateAllTests()
    {
        var inputDir = Path.Combine(_tempDir, "Input");
        var outputDir = Path.Combine(_tempDir, "Output");
        Directory.CreateDirectory(inputDir);
        Directory.CreateDirectory(outputDir);
        
        var files = new Dictionary<string, string>
        {
            ["UserService.cs"] = "public class UserService { public void Create() { } }",
            ["ProductService.cs"] = "public class ProductService { public void Update() { } }",
            ["OrderService.cs"] = "public class OrderService { public void Delete() { } }"
        };
        
        var inputFiles = new List<string>();
        foreach (var (fileName, content) in files)
        {
            var path = Path.Combine(inputDir, fileName);
            await File.WriteAllTextAsync(path, content);
            inputFiles.Add(path);
        }
        
        var pipeline = new TestGenerationPipeline(new NUnitTestGenerator());
        
        await pipeline.ProcessAsync(inputFiles, outputDir);
        
        foreach (var fileName in files.Keys)
        {
            var testFileName = fileName.Replace(".cs", "Tests.cs");
            Assert.That(File.Exists(Path.Combine(outputDir, testFileName)), Is.True);
        }
    }
}